### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 9dolanla** [Tuke-Nuke/TuSKe#101]
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! [Skript] Severe Error:
[19:01:14 ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Something went horribly wrong with Skript.
[19:01:14 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[19:01:14 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[19:01:14 ERROR]: #!#! Following plugins are probably related to this error in some way:
[19:01:14 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe)
[19:01:14 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[19:01:14 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[19:01:14 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[19:01:14 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[19:01:14 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Stack trace:
[19:01:14 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "ch.njol.skript.classes.ClassInfo.getChanger()" because the return value of "ch.njol.skript.registrations.Classes.getExactClassInfo(java.lang.Class)" is null
[19:01:14 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[19:01:14 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[19:01:14 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:466)
[19:01:14 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[19:01:14 ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[19:01:14 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:01:14 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:01:14 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:01:14 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[19:01:14 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[19:01:14 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[19:01:14 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[19:01:14 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[19:01:14 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[19:01:14 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Version Information:
[19:01:14 ERROR]: #!#!   Skript: 2.6-alpha1 (custom version)
[19:01:14 ERROR]: #!#!     Flavor: selfbuilt-unknown
[19:01:14 ERROR]: #!#!     Date: unknown
[19:01:14 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[19:01:14 ERROR]: #!#!   Minecraft: 1.16.5
[19:01:14 ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[19:01:14 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Server platform: Paper
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Current node: null
[19:01:14 ERROR]: #!#! Current item: null
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Thread: Server thread
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! Language: english
[19:01:14 ERROR]: #!#! Link parse mode: DISABLED
[19:01:14 ERROR]: #!#!
[19:01:14 ERROR]: #!#! End of Error.
[19:01:14 ERROR]: #!#!

**Comment by JustSkeppYT** [comment]
TuSke doesn't support 1.16.5
