### ISSUE TITLE
Error while generating json documentations (v1.8.2-dev.3)

### ISSUE THREAD

**Issue by Duetro** [Tuke-Nuke/TuSKe#11]
**Stacktrace:**
`[18:55:38 WARN]: [TuSKe] Plugin TuSKe v1.8.2-dev.3 generated an exception while executing task 8
java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
        at com.github.tukenuke.tuske.documentation.JsonFile.getJsonSyntax(JsonFile.java:60) ~[?:?]
        at com.github.tukenuke.tuske.documentation.JsonFile.addSection(JsonFile.java:42) ~[?:?]
        at com.github.tukenuke.tuske.documentation.JsonFile.write(JsonFile.java:30) ~[?:?]
        at com.github.tukenuke.tuske.documentation.Documentation.run(Documentation.java:97) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Tried on:**
CraftBukkit version git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) & 2.2-dev25 (bensku's fork)
CraftBukkit version git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) & 2.2-dev29 (bensku's fork)
Paper version git-Paper-1104 (MC: 1.11.2) & 2.2-dev25 (bensku's fork)
Paper version git-Paper-1104 (MC: 1.11.2) & 2.2-dev29 (bensku's fork)

**TuSKe's Config:**
https://pastebin.com/WdZ9CWUb

**Plugins:**
Only Skript & TuSKe

**Comment by Tuke-Nuke** [comment]
I tested json in 1.12 only, since it is using a third party library (which is present in Bukkit aswell), it is certainly conflicting between versions (e.g Bukkit using an old version of it while TuSKe requires a new one which is present in 1.12).
Thank's for reporting it, I will try it tonight if not, tomorrow.

**Comment by Tuke-Nuke** [comment]
I think I've fixed it in latest build.
