### ISSUE TITLE
Cancel Drops

### ISSUE THREAD

**Issue by UnknwonPerson** [Tuke-Nuke/TuSKe#2]
#!#!
[20:33:35] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[20:33:35] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[20:33:35] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[20:33:35] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[20:33:35] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[20:33:35] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[20:33:35] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! Stack trace:
[20:33:35] [Server thread/ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.entity.EntityDeathEvent cannot be cast to org.bukkit.event.entity.PlayerDeathEvent
[20:33:35] [Server thread/ERROR]: #!#! at me.tuke.sktuke.effects.EffCancelDrop.execute(EffCancelDrop.java:40)
[20:33:35] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:33:35] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[20:33:35] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:33:35] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:33:35] [Server thread/ERROR]: #!#! at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[20:33:35] [Server thread/ERROR]: #!#! at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[20:33:35] [Server thread/ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:33:35] [Server thread/ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:33:35] [Server thread/ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:33:35] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:363)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:868)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityHorse.die(EntityHorse.java:697)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:806)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityHorse.damageEntity(EntityHorse.java:259)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityLiving.K(EntityLiving.java:173)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityInsentient.K(EntityInsentient.java:149)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.Entity.s_(Entity.java:245)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityLiving.s_(EntityLiving.java:1438)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityInsentient.s_(EntityInsentient.java:193)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.EntityHorse.s_(EntityHorse.java:749)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1604)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.World.g(World.java:1579)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1422)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[20:33:35] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[20:33:35] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:745)
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! Version Information:
[20:33:35] [Server thread/ERROR]: #!#! Skript: 2.2-dev24b
[20:33:35] [Server thread/ERROR]: #!#! Bukkit: 1.8-R0.1-SNAPSHOT
[20:33:35] [Server thread/ERROR]: #!#! Minecraft: 1.8
[20:33:35] [Server thread/ERROR]: #!#! Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)
[20:33:35] [Server thread/ERROR]: #!#! OS: Linux amd64 4.2.0-27-generic
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! Current node: null
[20:33:35] [Server thread/ERROR]: #!#! Current item: cancel drop
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! Thread: Server thread
[20:33:35] [Server thread/ERROR]: #!#!
[20:33:35] [Server thread/ERROR]: #!#! End of Error.
[20:33:35] [Server thread/ERROR]: #!#!

**Comment by Syst3ms** [comment]
The effect is made to work on player deaths only. But @Tuke-Nuke could easily add it.

**Comment by Tuke-Nuke** [comment]
I forgot to say that I saw this error in Bensku's fork and it was already fixed. I only tested it in old Skript's fork for 1.8 and it might be causing only in new versions.
I'm just waiting cause I'm investigating another issue, so I will update asap.
Thank's for reporting it.
