### ISSUE TITLE
java.lang.IllegalArgumentException: Permission name cannot be null

### ISSUE THREAD

**Issue by Ex-Infinityy** [Tuke-Nuke/TuSKe#24]
[15:36:43] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Skript v2.2-dev32
java.lang.IllegalArgumentException: Permission name cannot be null
at org.bukkit.permissions.PermissibleBase.addAttachment(PermissibleBase.java:197) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:128) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]at com.github.tukenuke.tuske.manager.gui.GUIManager$1.onClick(GUIManager.java:149) ~[?:?]at com.github.tukenuke.tuske.listeners.GUIListener.onEvent(GUIListener.java:57) ~[?:?]at com.github.tukenuke.tuske.manager.gui.v2.SkriptGUIEvent.check(SkriptGUIEvent.java:39) ~[?:?]at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:145) ~[?:?]at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109) ~[?:?]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

**Comment by Pugabyte** [comment]
Add `with permission %string%` at the end of any gui lines that make the player run a command. This is a problem with the latest commit and will probably be fixed soon
