### ISSUE TITLE
Error with virtual GUI with skript dev 32-d and Tuske 1.8.2

### ISSUE THREAD

**Issue by DevilishDante** [Tuke-Nuke/TuSKe#36]
hi i have this error when a non op player open a virtual gui
````
02:17:04 INFO]: Saya_ issued server command: /menu
[02:17:04 INFO]: Saya_ [cbb05ad3-f96f-4ee3-ab8d-6d2f89fc0dca]: /menu
[02:17:07 WARN]: [TuSKe] Task #208304 for TuSKe v1.8.2 generated an exception
java.lang.IllegalArgumentException: Permission name cannot be null
        at org.bukkit.permissions.PermissibleBase.addAttachment(PermissibleBase.java:197) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:128) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]
        at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by Pikachu920** [comment]
use this patched version of tuske https://drive.google.com/file/d/1nEXrlY_zFxd8a_d3tqrFBIxSZ2Qm5jZj/view

**Comment by DevilishDante** [comment]
thanks :D i try it soon as possible :)
