### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PlesCZ** [Tuke-Nuke/TuSKe#39]
> [20:40:12 INFO]: [TuSKe] Enabling TuSKe v1.8.2 
> [20:40:12 ERROR]: Error occurred while enabling TuSKe v1.8.2 (Is it up to date?) 
java.lang.NoSuchMethodError: ch.njol.skript.bukkitutil.PlayerUtils.getOnlinePlayers()Ljava/util/Collection; 
at com.github.tukenuke.tuske.listeners.OnlineStatusCheck.<init>(OnlineStatusCheck.java:23) ~[?:?] 
at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:73) ~[?:?] 
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-db6de12-18fbb24] 
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24] 
at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins%20v1.1.0.jar:?] 
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24] 
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24] 
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-db6de12-18fbb24] 
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by PlesCZ** [comment]
FIX! :D PLEASE

**Comment by Pikachu920** [comment]
update your skript

**Comment by PlesCZ** [comment]
What?

**Comment by PlesCZ** [comment]
[10:27:24 ERROR]: Error occurred while enabling Skellett v1.9.6b (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/SpawnerSpawnEvent
        at com.gmail.thelimeglass.Register.events(Register.java:721) ~[?:?]
        at com.gmail.thelimeglass.Skellett.onEnable(Skellett.java:169) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.SpawnerSpawnEvent
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
        ... 13 more

**Comment by Syst3ms** [comment]
Download the latest version

**Comment by PlesCZ** [comment]
I have last version
