### ISSUE TITLE
Evaluate function without arguments doesn't work

### ISSUE THREAD

**Issue by bi0qaw** [Tuke-Nuke/TuSKe#40]
Evaluating a function without any arguments doesn't seem to work.

```
function fun():
    broadcast "called fun"

on load:
    evaluate function "fun"     # Raises an array out of index exception
    evaluate function "fun"()  # Raises a "can't understand this condition..." error on reload
```

Stack trace of exception:
```
[21:35:29 ERROR]: #!#! Stack trace:
[21:35:29 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
[21:35:29 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.getParameter(Function.java:56)
[21:35:29 ERROR]: #!#!     at com.github.tukenuke.tuske.util.EvalFunction.getParemetersValues(EvalFunction.java:85)
[21:35:29 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffEvaluateFunction.execute(EffEvaluateFunction.java:51)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:61)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:675)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:694)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[21:35:29 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[21:35:29 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:35:29 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:35:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[21:35:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:627)
[21:35:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443)
[21:35:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:35:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:35:29 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:35:29 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[21:35:29 ERROR]: #!#! 
[21:35:29 ERROR]: #!#! Version Information:
[21:35:29 ERROR]: #!#!   Skript: 2.2-dev32d (latest)
[21:35:29 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[21:35:29 ERROR]: #!#!   Minecraft: 1.12
[21:35:29 ERROR]: #!#!   Java: 1.8.0_102 (Java HotSpot(TM) 64-Bit Server VM 25.102-b14)
[21:35:29 ERROR]: #!#!   OS: Mac OS X x86_64 10.11.6
[21:35:29 ERROR]: #!#! 
[21:35:29 ERROR]: #!#! Running CraftBukkit: false
[21:35:29 ERROR]: #!#! Running Spigot (or compatible): true
[21:35:29 ERROR]: #!#! Running Paper (or compatible): false
[21:35:29 ERROR]: #!#! 
[21:35:29 ERROR]: #!#! Current node: null
[21:35:29 ERROR]: #!#! Current item: evaluate function "a"()
[21:35:29 ERROR]: #!#! Thread: Server thread
[21:35:29 ERROR]: #!#! 
[21:35:29 ERROR]: #!#! Language: english
[21:35:29 ERROR]: #!#! Link parse mode: DISABLED
[21:35:29 ERROR]: #!#! 
[21:35:29 ERROR]: #!#! End of Error.

```

**Comment by Syst3ms** [comment]
This had been made at the time when no argument functions weren't possible, I think.

**Comment by bi0qaw** [comment]
Possible, but they are now:)

**Comment by Pikachu920** [comment]
do no argument functions the old way. probably works
