### ISSUE TITLE
TuSKe errors on enable

### ISSUE THREAD

**Issue by Sitieno14** [Tuke-Nuke/TuSKe#51]
```
[15:07:07 ERROR]: #!#! [Skript] Severe Error:
[15:07:07 ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[15:07:07 ERROR]: #!#! 
[15:07:07 ERROR]: #!#! Something went horribly wrong with Skript.
[15:07:07 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:07:07 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:07:07 ERROR]: #!#! Following plugins are probably related to this error in some way:
[15:07:07 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
15:07:07 ERROR]: #!#! Stack trace:
[15:07:07 ERROR]: #!#! java.lang.NullPointerException
[15:07:07 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[15:07:07 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[15:07:07 ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[15:07:07 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[15:07:07 ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[15:07:07 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:07:07 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[15:07:07 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:07:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[15:07:07 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[15:07:07 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[15:07:07 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[15:07:07 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[15:07:07 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[15:07:07 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[15:07:07 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[15:07:07 ERROR]: #!#! 
[15:07:07 ERROR]: #!#! Version Information:
[15:07:07 ERROR]: #!#!   Skript: 2.2-dev35b
[15:07:07 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[15:07:07 ERROR]: #!#!   Minecraft: 1.12.2
[15:07:07 ERROR]: #!#!   Java: 1.8.0_162 (OpenJDK 64-Bit Server VM 25.162-b12)
[15:07:07 ERROR]: #!#! 
```

**Comment by HYPExMon5ter** [comment]
Use this to fix it https://cdn.discordapp.com/attachments/399406334526750723/440604232874197002/TuSKe-PikachuPatch-v2.jar

**Comment by bolleboor** [comment]
Some issue here.
My server is running 1.12.2 and I have exactly the same error as you.
The PikachuPatch worked as a fix!

Thanks !!!

> Use this to fix it https://cdn.discordapp.com/attachments/399406334526750723/440604232874197002/TuSKe-PikachuPatch-v2.jar
