### ISSUE TITLE
Logs error when no permissions are required to use an item

### ISSUE THREAD

**Issue by Guarmanda** [Tuke-Nuke/TuSKe#52]
At the begining, the first code was working. But after 3 or 4 hours, after some reload and a server restart, I got an error using that code and had to change it. I restarted the server to make sure the plugin was loading correctly, but I still had to put a permission to use the item. Else, it would return an error

```format gui slot 10 of player with 98:0 named "&1Serveur créatif" to close then run player command "/creatif"```
 --> worked at first, but throwed error messages after a while
```[14:11:13] [Server thread/WARN]: [TuSKe] Task #578 for TuSKe v1.8.2 generated an exception
java.lang.NullPointerException: permission
    at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.addAttachment(LPPermissible.java:235) ~[?:?]
    at me.lucko.luckperms.bukkit.model.permissible.LPPermissible.addAttachment(LPPermissible.java:64) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:128) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]
    at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]
    at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]
    at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-v1_12_2.jar:git-Spigot-7754231-94b0980]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

```format gui slot 10 of player with 98:0 named "&1Serveur créatif" to close then run player command "/creatif" with permission "staff"```
 --> No errors, still working, but I have to put a basic permission that everyone has to each gui item

**Comment by Pugabyte** [comment]
Are you on the latest version? This was fixed a long time ago in #29

**Comment by Guarmanda** [comment]
It was fixed the 30/09/2017 and the last version is from the  05/09/2017... So the problem isn't fixed in the last version

**Comment by Pugabyte** [comment]
http://dl.bear-nation.net/?q=tuske
