### ISSUE TITLE
generating error

### ISSUE THREAD

**Issue by firebl0od** [Tuke-Nuke/TuSKe#58]
/ERROR]: #!#! 
/ERROR]: #!#! [Skript] Severe Error:
/ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
/ERROR]: #!#! 
/ERROR]: #!#! Something went horribly wrong with Skript.
/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
/ERROR]: #!#! Following plugins are probably related to this error in some way:
/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
/ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)

/ERROR]: #!#! Stack trace:
/ERROR]: #!#! java.lang.NullPointerException
/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)

/ERROR]: #!#! Version Information:
/ERROR]: #!#!   Skript: 2.2-dev35b
/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
/ERROR]: #!#!   Minecraft: 1.12.2
/ERROR]: #!#!   Java: 1.8.0_121 (OpenJDK 64-Bit Server VM 25.121-b13)
/ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64

/ERROR]: #!#! Server platform: Spigot

/ERROR]: #!#! Current node: null
/ERROR]: #!#! Current item: null

/ERROR]: #!#! Thread: Server thread

/ERROR]: #!#! Language: english
/ERROR]: #!#! Link parse mode: DISABLED

/ERROR]: #!#! End of Error.

/INFO]: [TuSKe] Loaded 8 events, 12 conditions, 20 effects, 61 expressions and 0 types. Have fun!`

**Comment by firebl0od** [comment]
issue allready open
