### ISSUE TITLE
1.12.2 Support?

### ISSUE THREAD

**Issue by ItsMCB** [Tuke-Nuke/TuSKe#59]
**I was using TuSK on my 1.12 developing server and it worked fine. I downloaded the newest version and put it on my main 1.12.2 server and got a huge error. I know 1.12.2 support isn't on the tested versions but I really want to use TuSK on my server.**

_LOG:
[00:41:53] [Server thread/INFO]: [TuSKe] Enabling TuSKe v1.8.2
[00:41:53] [Server thread/INFO]: [TuSKe] Enabling Metrics... Done!
[00:41:53] [Server thread/INFO]: [TuSKe] Check for updates enabled. It will check in some seconds.
[00:41:53] [Server thread/INFO]: [TuSKe] Documentation enabled. Some files containing all syntax of all addons will be generated.
[00:41:53] [Server thread/INFO]: [TuSKe]  
[00:41:53] [Server thread/INFO]: [TuSKe]  A special thanks for donators:
[00:41:53] [Server thread/INFO]: [TuSKe]  @X0Freak - 50$
[00:41:53] [Server thread/INFO]: [TuSKe]  @RepublicanSensei - 10$
[00:41:53] [Server thread/INFO]: [TuSKe]  
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:41:53] [Server thread/ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[00:41:53] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:41:53] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:41:53] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
[00:41:53] [Server thread/ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
[00:41:53] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:41:53] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:41:53] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:41:53] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:41:53] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[00:41:53] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Stack trace:
[00:41:53] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[00:41:53] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[00:41:53] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[00:41:53] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[00:41:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[00:41:53] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[00:41:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:41:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[00:41:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[00:41:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[00:41:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[00:41:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[00:41:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[00:41:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[00:41:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[00:41:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[00:41:53] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Version Information:
[00:41:53] [Server thread/ERROR]: #!#!   Skript: 2.2-dev36
[00:41:53] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[00:41:53] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[00:41:53] [Server thread/ERROR]: #!#!   Java: 1.8.0_172 (Java HotSpot(TM) 64-Bit Server VM 25.172-b11)
[00:41:53] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-20-generic
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Server platform: Spigot
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Current node: null
[00:41:53] [Server thread/ERROR]: #!#! Current item: null
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Thread: Server thread
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! Language: english
[00:41:53] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/ERROR]: #!#! End of Error.
[00:41:53] [Server thread/ERROR]: #!#! 
[00:41:53] [Server thread/INFO]: [TuSKe] Loaded 8 events, 12 conditions, 20 effects, 62 expressions and 0 types. Have fun!_

**Comment by HYPExMon5ter** [comment]
Read the other issues before making a new one, there is already 3 issues opened with this, and it does support 1.12.2, this is just an error because of the new item system in skript, it doesn't break anything, but if you want a fix go check out issue #55, #53 or #51

**Comment by SenkiDaKitty** [comment]
Same, and patch doesn't work
