### ISSUE TITLE
Recent issue after the dev37a-c update

### ISSUE THREAD

**Issue by Squidddle19** [Tuke-Nuke/TuSKe#64]
I was having no problems at all until the most recent skript update. I have reverted back to dev36 version of skript and it works. I have removed tuske while on dev37c and don't get any issues.

`[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! [Skript] Severe Error:
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Something went horribly wrong with Skript.
[01:09:19 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[01:09:19 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[01:09:19 ERROR]: #!#! Here is full list of them:
[01:09:19 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) LargeSk (http://github.com/Nicofisi/LargeSk) TuSKe (github.com/Tuke-Nuke/TuSKe) skDragon MundoSK (https://forums.skunity.com/resources/mundosk.69/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) Umbaska SharpSK
[01:09:19 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[01:09:19 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[01:09:19 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[01:09:19 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[01:09:19 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[01:09:19 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[01:09:19 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Stack trace:
[01:09:19 ERROR]: #!#! java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.WeakHashMap
[01:09:19 ERROR]: #!#!     at com.github.tukenuke.tuske.util.VariableUtil.<init>(VariableUtil.java:24)
[01:09:19 ERROR]: #!#!     at com.github.tukenuke.tuske.util.VariableUtil.getInstance(VariableUtil.java:17)
[01:09:19 ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffMakeGUI.execute(EffMakeGUI.java:77)
[01:09:19 ERROR]: #!#!     at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:52)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:61)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:727)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:746)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:391)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:403)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:436)
[01:09:19 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[01:09:19 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:09:19 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:09:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[01:09:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[01:09:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[01:09:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[01:09:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[01:09:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[01:09:19 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Version Information:
[01:09:19 ERROR]: #!#!   Skript: 2.2-dev37c (latest)
[01:09:19 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[01:09:19 ERROR]: #!#!   Minecraft: 1.12.2
[01:09:19 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[01:09:19 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Server platform: Spigot
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Current node: null
[01:09:19 ERROR]: #!#! Current item: make  a gui slot [[long:0]] of gui with (lore >> ch.njol.skript.classes.data.DefaultConverters$13@48beac91: ch.njol.skript.aliases.ItemType->org.bukkit.inventory.ItemStack)
[01:09:19 ERROR]: #!#! Current trigger: script load (script load) (shop.sk, line 4)
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Thread: Server thread
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! Language: english
[01:09:19 ERROR]: #!#! Link parse mode: DISABLED
[01:09:19 ERROR]: #!#!
[01:09:19 ERROR]: #!#! End of Error.
[01:09:19 ERROR]: #!#!`

**Comment by Pikachu920** [comment]
use my fork

**Comment by Squidddle19** [comment]
Could you direct me to that fork, I'm not sure where I would find that
