### ISSUE TITLE
Error related to EffMakeDrop

### ISSUE THREAD

**Issue by leonidesu** [Tuke-Nuke/TuSKe#74]
Hi, I got this error everytime I start my server. I don't even know what kind of error this is but I could copy you the error from the console.
```
[07:39:46 ERROR]: #!#!                                                                                                                                         [40/612]
[07:39:46 ERROR]: #!#! [Skript] Severe Error:
[07:39:46 ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Something went horribly wrong with Skript.
[07:39:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[07:39:46 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[07:39:46 ERROR]: #!#! Following plugins are probably related to this error in some way:
[07:39:46 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe)
[07:39:46 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[07:39:46 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[07:39:46 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[07:39:46 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[07:39:46 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Stack trace:
[07:39:46 ERROR]: #!#! java.lang.NullPointerException
[07:39:46 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[07:39:46 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[07:39:46 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:398)
[07:39:46 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[07:39:46 ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[07:39:46 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[07:39:46 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[07:39:46 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[07:39:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[07:39:46 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[07:39:46 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[07:39:46 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[07:39:46 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[07:39:46 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[07:39:46 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[07:39:46 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Version Information:
[07:39:46 ERROR]: #!#!   Skript: 2.3.6 (latest)
[07:39:46 ERROR]: #!#!     Flavor: skriptlang-github
[07:39:46 ERROR]: #!#!     Date: 2019-03-03
[07:39:46 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[07:39:46 ERROR]: #!#!   Minecraft: 1.13.2
[07:39:46 ERROR]: #!#!   Java: 11.0.3 (OpenJDK 64-Bit Server VM 11.0.3+7-Ubuntu-1ubuntu218.04.1)
[07:39:46 ERROR]: #!#!   OS: Linux amd64 4.15.0-48-generic
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Server platform: Paper
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Current node: null
[07:39:46 ERROR]: #!#! Current item: null
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Thread: Server thread
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! Language: english
[07:39:46 ERROR]: #!#! Link parse mode: DISABLED
[07:39:46 ERROR]: #!#!
[07:39:46 ERROR]: #!#! End of Error.
[07:39:46 ERROR]: #!#!

```
I hope this will help.

**Comment by TheAberto** [comment]
Yes i get the error too. https://paste.ubuntu.com/p/h37vr5p5QW/
