### ISSUE TITLE
TuSKe 1.12.2 GUI

### ISSUE THREAD

**Issue by ghost** [Tuke-Nuke/TuSKe#76]
Hey! Im using TuSKe (the newest version) for my server and i want to create a gui, Its working perfect but 1 thing doesn't work and that is what i want to use!
Code:

command /menu:
	trigger:
		open chest with 3 rows named "&6Menu" to player 
		create a gui slot 1 of player with green wool named "&aMenu Button" to close: 
			message "&5Hello" 

The gui doesn't show up
and the [**to close:**] doesn't work

Can someone help me please?

**Comment by AmarProGamer** [comment]
Your using skquery to open the gui and tuske to format it... and im pretty sure its  "to close then run:"

**Comment by leonidesu** [comment]
True, there is something wrong with TuSKe GUI. I tried to execute this
`format gui slot 2 of player with stone shovel named "&aExcavator" with lore "&6Description:", "&eDapatkan EXP / uang dengan melakukan", "&edigging dan mining.", "", "&6McMMO:", "&e- Excavation: Giga Drill", "&e- Mining: Super Breaker", "", "&6Tier 3:" and "&bDigger, Miner" to close then run function levelupTier2(player, Excavator)`
Turns out got an error like this
```
[15:16:44 INFO]: GebokLebok [bd7f00e1-e549-3c1c-ad7d-d1c72e540407]: /uptier                                                                 │··························
[15:16:45 WARN]: [TuSKe] Task #5650 for TuSKe v1.8.2-Pikachu-Patch-3 generated an exception                                                 │··························
java.lang.NullPointerException: null                                                                                                        │··························
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:83) ~[?:?]                                               │··························
        at ch.njol.skript.lang.function.Function.execute(Function.java:119) ~[?:?]                                                          │··························
        at com.github.tukenuke.tuske.util.EvalFunction.run(EvalFunction.java:101) ~[?:?]                                                    │··························
        at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]                                                                │··························
        at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146) ~[?:?]                                  │··························
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-629]                   │··························
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Pa│··························
per-629]                                                                                                                                    │··························
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-629]                   │··························
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-629]                    │··························
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-629]                    │··························
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-629]                  │··························
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Fyi, I'm using pikachu's fork of TuSKe and latest version of skript (bensku).
I hope this will help.
