### ISSUE TITLE
Error With GUI Click Event Using TuSKe

### ISSUE THREAD

**Issue by Gleemed** [Tuke-Nuke/TuSKe#82]
When a player who is not OP tries to click an item in the GUI the console gets this command -

`24.01 23:31:23 [Server] WARN [TuSKe] Task #4559 for TuSKe v1.8.2 generated an exception
24.01 23:31:23 [Server] INFO java.lang.IllegalArgumentException: Permission name cannot be null
24.01 23:31:23 [Server] INFO at org.bukkit.permissions.PermissibleBase.addAttachment(PermissibleBase.java:197) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:118) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]
24.01 23:31:23 [Server] INFO at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]
24.01 23:31:23 [Server] INFO at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]
24.01 23:31:23 [Server] INFO at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146) ~[?:?]
24.01 23:31:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
24.01 23:31:23 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222`

I am running the latest version of TuSKe along with dev36 of Skript (as my server is 1.8.8)
I have looked at the other issues with this same problem but I can't figure out the solution.

**Comment by Gleemed** [comment]
Okay. After looking some more I got a Version of the Pikachu Patch that fixed this problem. Took a bit to find though.
