### ISSUE TITLE
GUI work only with OP users

### ISSUE THREAD

**Issue by Mhorker** [Tuke-Nuke/TuSKe#88]
`java.lang.IllegalArgumentException: Permission name cannot be null
        at org.bukkit.permissions.PermissibleBase.addAttachment(PermissibleBase.java:219) ~[patched_1.15.2.jar:git-Paper-301]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:252) ~[patched_1.15.2.jar:git-Paper-301]
        at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]
        at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-301]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-301]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[20:58:11 WARN]: Can't keep up! Is the server overloaded? Running 23109ms or 462 ticks behind`

**Comment by brobie1kanobi** [comment]
### Not sure if poster is on this same version, but I can confirm on 1.8.2

Here is (part of) a test code I use/to use to recreate the issue:

```
command warpgui:
  trigger:
    set {pane} to random element of {panes::*}
    open virtual chest inventory with size 6 named "&1&l             Games&r" to player
    format gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 49, 50, 51, 52 and 53 of player with {pane} named "&bJust glass!" with lore "&5Why are you reading this?" and "&5It's just glass, stop reading already!"
    format gui slot 10 of player with paper named "&2&lPark" with lore "TP to" and "the park" to close then run player command "park"
    format gui slot 12 of player with slime block named "&2&lFun house" with lore "&5Try out the" and "&5fun Funhouse." to close then run player command "warp funhouse"

obviously more here
```
`↑ This throws no errors when reloading ↑`

1. The "park" command is a script command with no perms to tp a player to a set location, which works when ran normally (chat command) on non-op.

2. The non-op has the warp permission and can use the commands requested normally.

3.  The gui works perfectly fine for OP account (which is of course, is how all of the skripts are tested).

Here is the error I get in console when clicking the item in the gui on my non-op'd alt:

```
[04:54:22 WARN]: [TuSKe] Task #767674 for TuSKe v1.8.2 generated an exception
java.lang.NullPointerException: permission
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_275]
        at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.addAttachment(LuckPermsPermissible.java:260) ~[?:?]
        at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissible.addAttachment(LuckPermsPermissible.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.addAttachment(CraftHumanEntity.java:226) ~[patched_1.16.4.jar:git-Paper-260]
        at com.github.tukenuke.tuske.util.CommandUtils.runCommand(CommandUtils.java:37) ~[?:?]
        at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.lambda$execute$0(EffFormatGUI.java:132) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29) ~[?:?]
        at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-260]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-260]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.4.jar:git-Paper-260]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-260]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-260]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-260]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-260]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by brobie1kanobi** [comment]
I know this is old, but it IS still an issue. Is @Tuke-Nuke still active? Or is @LimeGlass able to do anything here?
