### ISSUE TITLE
[BUG] Unknown error

### ISSUE THREAD

**Issue by Command1264** [Tuke-Nuke/TuSKe#91]
### Description
use tuske's gui with skript-placeholders (placeholders from loop-value)

### Steps to Reproduce
1.add named "§r§r%placeholder ""cmi_user_display_name"" from loop-value%" to  format gui slot {_a} of {_p} with paper
2.reload .sk
3.open gui
4. see error

### Expected Behavior
show item's name with "cmi_user_display_name"

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/50344708/83935513-d96ad880-a7ec-11ea-8448-5e8b62338df2.png)

[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:52:56] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:52:56] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:52:56] [Server thread/ERROR]: #!#! Here is full list of them:
[11:52:56] [Server thread/ERROR]: #!#! skRayFall v1.9.20 (https://sk.rayfall.net/) skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror) Skungee v1.0.13 TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) ItemsAdder v2.0.26 (matteodev.it) skDragon v0.16 SkBee v1.3.3 skript-yaml v1.2.5 SkQuery v3.6.5 Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) skript-placeholders v1.4 (https://github.com/APickledWalrus/skript-placeholders) Skent v1.10
[11:52:56] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:52:56] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:52:56] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:52:56] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:52:56] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:52:56] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Stack trace:
[11:52:56] [Server thread/ERROR]: #!#! java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.bukkit.OfflinePlayer;
[11:52:56] [Server thread/ERROR]: #!#!     at io.github.apickledwalrus.placeholderaddon.skript.expressions.ExprParsePlaceholder.get(ExprParsePlaceholder.java:104)
[11:52:56] [Server thread/ERROR]: #!#!     at io.github.apickledwalrus.placeholderaddon.skript.expressions.ExprParsePlaceholder.get(ExprParsePlaceholder.java:23)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:477)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:721)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprNamed.get(ExprNamed.java:75)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:160)
[11:52:56] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:117)
[11:52:56] [Server thread/ERROR]: #!#!     at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[11:52:56] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[11:52:56] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[11:52:56] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[11:52:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[11:52:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[11:52:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[11:52:56] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[11:52:56] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Version Information:
[11:52:56] [Server thread/ERROR]: #!#!   Skript: 2.5-alpha3 (latest)
[11:52:56] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[11:52:56] [Server thread/ERROR]: #!#!     Date: 2020-03-28
[11:52:56] [Server thread/ERROR]: #!#!   Bukkit: 1.15.2-R0.1-SNAPSHOT
[11:52:56] [Server thread/ERROR]: #!#!   Minecraft: 1.15.2
[11:52:56] [Server thread/ERROR]: #!#!   Java: 1.8.0_251 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08)
[11:52:56] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Server platform: Spigot
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Current node: null
[11:52:56] [Server thread/ERROR]: #!#! Current item: format a gui slot {_a}(as java.lang.Number) of {_p}(as org.bukkit.entity.Player) with ([[itemtype:piece of paper]] named "§r§r%the value of placeholder(s) "cmi_user_display_name" from loop-value%" >> ch.njol.skript.classes.data.DefaultConverters$14@55492f0e: itemtype -> itemstack)
[11:52:56] [Server thread/ERROR]: #!#! Current trigger: function gui (simple event) (玩家列表.sk, line -1)
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Thread: Server thread
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! Language: english
[11:52:56] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[11:52:56] [Server thread/ERROR]: #!#!
[11:52:56] [Server thread/ERROR]: #!#! End of Error.
[11:52:56] [Server thread/ERROR]: #!#!

### Server Information
* **Server version/platform:**     Spigot 1.15.2
* **tuske version:**                1.8.2-Pikachu-Patch-3
* **Skript version:**                2.5-alpha3

**Comment by JustSkeppYT** [comment]
TuSke doesn't work on 1.11+

It's recommended to use alternatives such as skript-gui, it's simple and usually within 15 days you're help is resolved.
skript-gui https://github.com/APickledWalrus/skript-gui
