### ISSUE TITLE
 Need help fixing TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading

### ISSUE THREAD

**Issue by CryptxzzX** [Tuke-Nuke/TuSKe#93]
[16:02:23 ERROR]: #!#! [Skript] Severe Error:
[16:02:23 ERROR]: #!#! TuSKe's class com.github.tukenuke.tuske.effects.EffMakeDrop generated an exception while loading
[16:02:23 ERROR]: #!#!
[16:02:23 ERROR]: #!#! Something went horribly wrong with Skript.
[16:02:23 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:02:23 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:02:23 ERROR]: #!#! Following plugins are probably related to this error in some way:
[16:02:23 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe)
[16:02:23 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:02:23 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:02:23 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:02:23 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:02:23 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:02:23 ERROR]: #!#!
[16:02:23 ERROR]: #!#! Stack trace:
[16:02:23 ERROR]: #!#! java.lang.NullPointerException
[16:02:23 ERROR]: #!#!     at com.github.tukenuke.tuske.effects.EffMakeDrop.<clinit>(EffMakeDrop.java:25)
[16:02:23 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[16:02:23 ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[16:02:23 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[16:02:23 ERROR]: #!#!     at com.github.tukenuke.tuske.TuSKe.onEnable(TuSKe.java:100)
[16:02:23 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:02:23 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:02:23 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:02:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[16:02:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[16:02:23 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[16:02:23 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[16:02:23 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[16:02:23 ERROR]: #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:02:23 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[16:02:23 ERROR]: #!#!
[16:02:23 ERROR]: #!#! Version Information:
[16:02:23 ERROR]: #!#!   Skript: 2.5 (latest)
[16:02:23 ERROR]: #!#!     Flavor: skriptlang-github
[16:02:23 ERROR]: #!#!     Date: 2020-09-24
[16:02:23 ERROR]: #!#!   Bukkit: 1.16.3-R0.1-SNAPSHOT
[16:02:23 ERROR]: #!#!   Minecraft: 1.16.3
[16:02:23 ERROR]: #!#!   Java: 1.8.0_241 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07)
[16:02:23 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[16:02:23 ERROR]: #!#!

**Comment by brobie1kanobi** [comment]
@CryptxzzX Are you still seeing this since updating to the latest version of TuSKe, Skript and (possibly) your server version?

**Comment by FNPCMDs** [comment]
> @CryptxzzX Are you still seeing this since updating to the latest version of TuSKe, Skript and (possibly) your server version?

Same issue here, everything is up to date

**Comment by MineMaster836** [comment]
I seem to be having the same problem with the same error and everything is up to date except im running a paper 1.16.4 server

**Comment by MrMcyeet** [comment]
Same issue on 1.12.2 paper
