### ISSUE TITLE
The "then run:" effect isn’t working anymore

### ISSUE THREAD

**Issue by ChezCoder** [Tuke-Nuke/TuSKe#94]
Code:
```vb
format gui slot 21 of {_p} with 1 red stained glass pane named "&cRemove 1" to run:
    send "test" to event-player
    send "hello" to event-player
```

Issue:
I did `/sk reload shopGui` and it went with no errors, but console spat out lots of them.

```
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! [Skript] Severe Error:
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Something went horribly wrong with Skript.
[11:37:42 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:37:42 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:37:42 ERROR]: #!#! Following plugins are probably related to this error in some way:
[11:37:42 ERROR]: #!#! TuSKe (github.com/Tuke-Nuke/TuSKe) 
[11:37:42 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:37:42 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:37:42 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:37:42 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:37:42 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Stack trace:
[11:37:42 ERROR]: #!#! java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.util.WeakHashMap (java.util.HashMap and java.util.WeakHashMap are in module java.base of loader 'bootstrap')
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.util.VariableUtil.<init>(VariableUtil.java:24)
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.util.VariableUtil.getInstance(VariableUtil.java:17)
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:141)
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.util.EffectSection.check(EffectSection.java:54)
[11:37:42 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[11:37:42 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:50)
[11:37:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[11:37:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[11:37:42 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89)
[11:37:42 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:135)
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.util.EvalFunction.run(EvalFunction.java:101)
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.GUI.run(GUI.java:29)
[11:37:42 ERROR]: #!#!     at com.github.tukenuke.tuske.manager.gui.GUIManager$1.lambda$onClick$0(GUIManager.java:146)
[11:37:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[11:37:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[11:37:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293)
[11:37:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[11:37:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)
[11:37:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
[11:37:42 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[11:37:42 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Version Information:
[11:37:42 ERROR]: #!#!   Skript: 2.5.3 (latest)
[11:37:42 ERROR]: #!#!     Flavor: skriptlang-github
[11:37:42 ERROR]: #!#!     Date: 2020-12-11
[11:37:42 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[11:37:42 ERROR]: #!#!   Minecraft: 1.16.5
[11:37:42 ERROR]: #!#!   Java: 14.0.2 (Java HotSpot(TM) 64-Bit Server VM 14.0.2+12-46)
[11:37:42 ERROR]: #!#!   OS: Mac OS X x86_64 10.14.6
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Server platform: Paper
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Current node: null
[11:37:42 ERROR]: #!#! Current item: format a gui slot [[long:21]] of {_p}(as org.bukkit.entity.Player) with ([[itemtype:red stained glass pane]] named "§cRemove 1" >> ch.njol.skript.classes.data.DefaultConverters$14@371fe6c2: itemtype -> itemstack)
[11:37:42 ERROR]: #!#! Current trigger: function buy (simple event) (shopGui.sk, line -1)
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Thread: Server thread
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! Language: english
[11:37:42 ERROR]: #!#! Link parse mode: DISABLED
[11:37:42 ERROR]: #!#! 
[11:37:42 ERROR]: #!#! End of Error.
[11:37:42 ERROR]: #!#! 
```

**Comment by Govindass** [comment]
TuSKe is no longer developed. alternatives are skript-gui and vanilla guis
